Fix the "deprecated" error on "Donation info" page in wp-admin ...
error: `PHP Deprecated:  preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in .../wp-includes/kses.php on line 1805

\Leyka_Gateway::display_donation_specific_data_fields() method is void actually.
It doesn't need nighter `echo` nor `wp_kses`.